### ISSUE TITLE
[Bugs] Sub - extended mantle duration

### ISSUE THREAD

**Issue by fuu1** [Ravenholdt-TC/Issues#37]
**Game Version:**
>Live 7.2.5.24430

**Description:**
> Mantle duration gets refreshed if you time shd right.

**Reproduce rate:**
>extremely low

**Details:**
> Time your shadowdance so that it ends the same time as mantle
> Edit: seems to work with Shadowmelt aswell

**Howto:**
> use shd so that it triggers when mantle duration has close to/exact 4 secounds left.
>i tryed reproducing it but i wasnt able to get it in the timeframe.

>2 logs showing it:
>[#1](https://goo.gl/4Lp3E9) (~203)
>[#2](https://goo.gl/rtCymk) (at the start)

**Comment by Ivvankov** [comment]
This may have been fixed - can't confirm, but it's not working anymore.

For a while I was able to continuously reproduce the results by creating a Recorded Delay custom macro in my Cataclysm mouse and editing the time delay between the 2 keys (one key broke stealth and the other activates Shadow Dance) in the XML file to accommodate for the difference in duration.

**Comment by fuu1** [comment]
the bug is still in the game:
[here is a log showing it](https://www.warcraftlogs.com/reports/WDZVNtMvXBY49Kzw/#fight=21&type=auras&source=20&view=timeline).

**Comment by leovdw** [comment]
Having an other case of this bug right there, whitch happend 2 times in total in raid.
![capture](https://user-images.githubusercontent.com/22907105/28894131-2a186dfc-77d4-11e7-889b-012196d0c775.PNG)

**Comment by Saryero** [comment]
[Still in the game as of today (7.3)](https://www.warcraftlogs.com/reports/WgjPvVGzcd3BT96y#fight=31&type=auras&source=5&view=timeline&start=9952388&end=9975830)

**Comment by Saryero** [comment]
[Still in the game as of 7.3.2](https://www.warcraftlogs.com/reports/Gk68DhzWB7ajwLt1#fight=24&type=auras&source=25&view=timeline&start=8101539&end=8121662)

**Comment by Mystler** [comment]
Closing for this for BfA.
